frame_id: world_frame
point_cloud_descriptions:
  - x: 0.95
    y: 0.2
    z: 0.36
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.1
    w: 0.19
    h: 0.0
    resolution: 0.0005
  - x: 1.1
    y: -0.1
    z: 0.1
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.2
    w: 0.1
    h: 0.0
    resolution: 0.0005
  - x: 0.7
    y: -0.5
    z: 0.3
    rx: 0.0
    ry: 0.0
    rz: 0.0
    l: 0.2
    w: 0.2
    h: 0.0
    resolution: 0.0005
